apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-photos-pvc
  labels:
    app: customer-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment and modify the following for specific storage class
  # storageClassName: standard